/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-zWLHjG/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "clk_f.v:1" *)
module  clk_1f_ys(clk_in, clk_1);
  (* src = "clk_f.v:8" *)
  wire _000_;
  (* src = "clk_f.v:8" *)
  wire [27:0] _001_;
  (* src = "clk_f.v:10" *)
  wire [27:0] _002_;
  wire [15:0] _003_;
  wire [7:0] _004_;
  wire [3:0] _005_;
  wire [1:0] _006_;
  (* src = "clk_f.v:11" *)
  wire _007_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [27:0] _008_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _009_;
  wire [31:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  (* src = "<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _015_;
  wire [31:0] _016_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _017_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _018_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _019_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _020_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _021_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _022_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _023_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _024_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _025_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _026_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _027_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _028_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _029_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _030_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _031_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _032_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _033_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _034_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _035_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _036_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _037_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _038_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _039_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _040_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _041_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _042_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _043_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _044_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _045_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _046_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _047_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _048_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _049_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _050_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _051_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _052_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _053_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _054_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _055_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _056_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _057_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _058_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _059_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _060_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _061_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _062_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _063_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _064_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _065_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _066_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _067_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _068_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _069_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _070_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _071_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _072_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _073_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _074_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _075_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _076_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _077_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _078_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _079_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _080_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _081_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _082_;
  (* src = "<techmap.v>:260|<techmap.v>:222" *)
  wire _083_;
  (* src = "<techmap.v>:260|<techmap.v>:221" *)
  wire _084_;
  (* src = "clk_f.v:3" *)
  output clk_1;
  reg clk_1;
  (* src = "clk_f.v:2" *)
  input clk_in;
  (* init = 28'b0000000000000000000000000100 *)
  (* src = "clk_f.v:5" *)
  reg [27:0] counter;
  initial counter = 28'b0000000000000000000000000100;
  assign _006_[0] = _005_[0] & _005_[1];
  assign _013_ = _006_[0] & _006_[1];
  assign _007_ = _012_ | _013_;
  assign _001_[20] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[20];
  assign _001_[21] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[21];
  assign _001_[22] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[22];
  assign _001_[23] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[23];
  assign _001_[24] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[24];
  assign _001_[25] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[25];
  assign _001_[26] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[26];
  assign _001_[27] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[27];
  assign _001_[0] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[0];
  assign _001_[1] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[1];
  assign _001_[2] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[2];
  assign _001_[3] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[3];
  assign _001_[4] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[4];
  assign _001_[5] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[5];
  assign _001_[6] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[6];
  assign _001_[7] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[7];
  assign _001_[8] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[8];
  assign _001_[9] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[9];
  assign _001_[10] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[10];
  assign _001_[11] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[11];
  assign _001_[12] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[12];
  assign _001_[13] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[13];
  assign _001_[14] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[14];
  assign _001_[15] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[15];
  assign _001_[16] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[16];
  assign _001_[17] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[17];
  assign _001_[18] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[18];
  assign _001_[19] = _007_ ? (* src = "clk_f.v:11" *) 1'b0 : _002_[19];
  assign _012_ = ~_014_;
  assign _011_ = ~_009_[31];
  assign _000_ = ~_015_[31];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      clk_1 <= _000_;
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[0] <= _001_[0];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[1] <= _001_[1];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[2] <= _001_[2];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[3] <= _001_[3];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[4] <= _001_[4];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[5] <= _001_[5];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[6] <= _001_[6];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[7] <= _001_[7];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[8] <= _001_[8];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[9] <= _001_[9];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[10] <= _001_[10];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[11] <= _001_[11];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[12] <= _001_[12];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[13] <= _001_[13];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[14] <= _001_[14];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[15] <= _001_[15];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[16] <= _001_[16];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[17] <= _001_[17];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[18] <= _001_[18];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[19] <= _001_[19];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[20] <= _001_[20];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[21] <= _001_[21];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[22] <= _001_[22];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[23] <= _001_[23];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[24] <= _001_[24];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[25] <= _001_[25];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[26] <= _001_[26];
  (* src = "clk_f.v:8" *)
  always @(posedge clk_in)
      counter[27] <= _001_[27];
  assign _004_[0] = _003_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _003_[0];
  assign _008_[7] = _028_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _004_[0];
  assign _008_[15] = _033_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _008_[7];
  assign _017_ = counter[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[4];
  assign _018_ = counter[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[6];
  assign _019_ = counter[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[8];
  assign _020_ = counter[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[10];
  assign _021_ = counter[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[12];
  assign _022_ = counter[15] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[14];
  assign _023_ = counter[17] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[16];
  assign _024_ = counter[19] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[18];
  assign _025_ = counter[21] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[20];
  assign _026_ = counter[23] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[22];
  assign _027_ = counter[25] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[24];
  assign _028_ = _018_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _017_;
  assign _029_ = _020_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _019_;
  assign _030_ = _022_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _021_;
  assign _031_ = _024_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _023_;
  assign _032_ = _026_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _025_;
  assign _033_ = _030_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _029_;
  assign _034_ = _032_ &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _031_;
  assign _008_[23] = _034_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[15];
  assign _008_[11] = _029_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[7];
  assign _008_[19] = _031_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[15];
  assign _008_[5] = _017_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _004_[0];
  assign _008_[9] = _019_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[7];
  assign _008_[13] = _021_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[11];
  assign _008_[17] = _023_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[15];
  assign _008_[21] = _025_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[19];
  assign _008_[25] = _027_ &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[23];
  assign _008_[6] = counter[6] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[5];
  assign _008_[8] = counter[8] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[7];
  assign _008_[10] = counter[10] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[9];
  assign _008_[12] = counter[12] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[11];
  assign _008_[14] = counter[14] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[13];
  assign _008_[16] = counter[16] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[15];
  assign _008_[18] = counter[18] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[17];
  assign _008_[20] = counter[20] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[19];
  assign _008_[22] = counter[22] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[21];
  assign _008_[24] = counter[24] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[23];
  assign _008_[26] = counter[26] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _008_[25];
  assign _003_[0] = counter[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[0];
  assign _035_ = _010_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[6];
  assign _038_ = _010_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[12];
  assign _041_ = _010_[19] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[18];
  assign _043_ = _010_[23] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[22];
  assign _048_ = _003_[7] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _061_;
  assign _051_ = _003_[13] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _067_;
  assign _005_[0] = _004_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _004_[0];
  assign _055_ = _005_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _009_[7];
  assign _057_ = _006_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _009_[15];
  assign _003_[1] = counter[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[2];
  assign _003_[2] = _010_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  counter[4];
  assign _003_[5] = _010_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[10];
  assign _003_[6] = _010_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[12];
  assign _003_[7] = _010_[15] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[14];
  assign _003_[10] = _010_[21] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[20];
  assign _003_[11] = _010_[23] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[22];
  assign _003_[12] = _010_[25] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[24];
  assign _003_[13] = _010_[27] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[26];
  assign _004_[4] = _003_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[8];
  assign _005_[2] = _004_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _004_[4];
  assign _006_[1] = _004_[6] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _005_[2];
  assign _008_[2] = counter[2] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _003_[0];
  assign _008_[4] = counter[4] &(* src = "<techmap.v>:260|<techmap.v>:229" *)  _004_[0];
  assign _059_ = counter[9] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _036_;
  assign _062_ = counter[15] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _039_;
  assign _063_ = counter[17] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _040_;
  assign _064_ = counter[19] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _041_;
  assign _065_ = counter[21] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _042_;
  assign _067_ = counter[25] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _044_;
  assign _068_ = counter[27] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _045_;
  assign _069_ = _058_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _046_;
  assign _070_ = _060_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _047_;
  assign _071_ = _062_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _048_;
  assign _072_ = _064_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _049_;
  assign _009_[7] = _069_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _005_[0];
  assign _074_ = _071_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _052_;
  assign _075_ = _073_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _053_;
  assign _009_[15] = _074_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _055_;
  assign _009_[31] = _076_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _057_;
  assign _077_ = _016_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _015_[0];
  assign _078_ = _016_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[2];
  assign _036_ = _010_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[8];
  assign _037_ = _010_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[10];
  assign _039_ = _010_[15] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[14];
  assign _040_ = _010_[17] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[16];
  assign _042_ = _010_[21] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[20];
  assign _044_ = _010_[25] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[24];
  assign _045_ = _010_[27] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[26];
  assign _079_ = _083_ &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _015_[1];
  assign _046_ = _003_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  counter[5];
  assign _047_ = _003_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _059_;
  assign _049_ = _003_[9] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _063_;
  assign _050_ = _003_[11] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _065_;
  assign _080_ = _004_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _015_[3];
  assign _052_ = _004_[3] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _070_;
  assign _053_ = _004_[5] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _072_;
  assign _081_ = _005_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _015_[7];
  assign _056_ = _004_[6] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _075_;
  assign _082_ = _006_[1] &(* src = "<techmap.v>:260|<techmap.v>:221" *)  _015_[15];
  assign _083_ = _016_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _016_[2];
  assign _003_[3] = _010_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[6];
  assign _003_[4] = _010_[9] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[8];
  assign _003_[8] = _010_[17] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[16];
  assign _003_[9] = _010_[19] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _010_[18];
  assign _004_[1] = _003_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[2];
  assign _004_[2] = _003_[5] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[4];
  assign _004_[3] = _003_[7] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[6];
  assign _004_[5] = _003_[11] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[10];
  assign _004_[6] = _003_[13] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _003_[12];
  assign _005_[1] = _004_[3] &(* src = "<techmap.v>:260|<techmap.v>:222" *)  _004_[2];
  assign _014_ = _011_ | _013_;
  assign _015_[0] = counter[0] |(* src = "<techmap.v>:260|<techmap.v>:212" *)  _002_[0];
  assign _015_[1] = counter[1] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _077_;
  assign _084_ = counter[3] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _078_;
  assign _058_ = counter[7] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _035_;
  assign _060_ = counter[11] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _037_;
  assign _061_ = counter[13] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _038_;
  assign _066_ = counter[23] |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _043_;
  assign _015_[3] = _084_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _079_;
  assign _073_ = _066_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _050_;
  assign _054_ = _068_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _051_;
  assign _015_[7] = _069_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _080_;
  assign _015_[15] = _074_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _081_;
  assign _076_ = _054_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _056_;
  assign _015_[31] = _076_ |(* src = "<techmap.v>:260|<techmap.v>:221" *)  _082_;
  assign _002_[5] = counter[5] ^(* src = "<techmap.v>:263" *)  _008_[4];
  assign _002_[6] = counter[6] ^(* src = "<techmap.v>:263" *)  _008_[5];
  assign _002_[7] = counter[7] ^(* src = "<techmap.v>:263" *)  _008_[6];
  assign _002_[8] = counter[8] ^(* src = "<techmap.v>:263" *)  _008_[7];
  assign _002_[9] = counter[9] ^(* src = "<techmap.v>:263" *)  _008_[8];
  assign _002_[10] = counter[10] ^(* src = "<techmap.v>:263" *)  _008_[9];
  assign _002_[11] = counter[11] ^(* src = "<techmap.v>:263" *)  _008_[10];
  assign _002_[12] = counter[12] ^(* src = "<techmap.v>:263" *)  _008_[11];
  assign _002_[13] = counter[13] ^(* src = "<techmap.v>:263" *)  _008_[12];
  assign _002_[14] = counter[14] ^(* src = "<techmap.v>:263" *)  _008_[13];
  assign _002_[15] = counter[15] ^(* src = "<techmap.v>:263" *)  _008_[14];
  assign _002_[16] = counter[16] ^(* src = "<techmap.v>:263" *)  _008_[15];
  assign _002_[17] = counter[17] ^(* src = "<techmap.v>:263" *)  _008_[16];
  assign _002_[18] = counter[18] ^(* src = "<techmap.v>:263" *)  _008_[17];
  assign _002_[19] = counter[19] ^(* src = "<techmap.v>:263" *)  _008_[18];
  assign _002_[20] = counter[20] ^(* src = "<techmap.v>:263" *)  _008_[19];
  assign _002_[21] = counter[21] ^(* src = "<techmap.v>:263" *)  _008_[20];
  assign _002_[22] = counter[22] ^(* src = "<techmap.v>:263" *)  _008_[21];
  assign _002_[23] = counter[23] ^(* src = "<techmap.v>:263" *)  _008_[22];
  assign _002_[24] = counter[24] ^(* src = "<techmap.v>:263" *)  _008_[23];
  assign _002_[25] = counter[25] ^(* src = "<techmap.v>:263" *)  _008_[24];
  assign _002_[26] = counter[26] ^(* src = "<techmap.v>:263" *)  _008_[25];
  assign _002_[27] = counter[27] ^(* src = "<techmap.v>:263" *)  _008_[26];
  assign _010_[5] = counter[5] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[6] = counter[6] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[7] = counter[7] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[8] = counter[8] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[9] = counter[9] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[10] = counter[10] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[11] = counter[11] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[12] = counter[12] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[13] = counter[13] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[14] = counter[14] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[15] = counter[15] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[16] = counter[16] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[17] = counter[17] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[18] = counter[18] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[19] = counter[19] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[20] = counter[20] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[21] = counter[21] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[22] = counter[22] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[23] = counter[23] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[24] = counter[24] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[25] = counter[25] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[26] = counter[26] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _010_[27] = counter[27] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _002_[0] = counter[0] ^(* src = "<techmap.v>:263" *)  1'b1;
  assign _002_[1] = counter[1] ^(* src = "<techmap.v>:263" *)  counter[0];
  assign _002_[2] = counter[2] ^(* src = "<techmap.v>:263" *)  _003_[0];
  assign _002_[3] = counter[3] ^(* src = "<techmap.v>:263" *)  _008_[2];
  assign _002_[4] = counter[4] ^(* src = "<techmap.v>:263" *)  _004_[0];
  assign _016_[1] = counter[1] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _016_[2] = counter[2] ^(* src = "<techmap.v>:262" *)  1'b1;
  assign _016_[3] = counter[3] ^(* src = "<techmap.v>:262" *)  1'b1;
endmodule
