/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "yosys_conv_8_32.v:5" *)
module yosys_conv_8_32(clk, valid_0, data_in, data_out, valid_out);
  (* src = "yosys_conv_8_32.v:13" *)
  wire [1:0] _000_;
  (* src = "yosys_conv_8_32.v:13" *)
  wire [31:0] _001_;
  (* src = "yosys_conv_8_32.v:13" *)
  wire [31:0] _002_;
  (* src = "yosys_conv_8_32.v:22" *)
  (* unused_bits = "2" *)
  wire [31:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire [1:0] _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:432" *)
  wire [15:0] _017_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:428" *)
  wire [7:0] _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:432" *)
  wire [15:0] _022_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:428" *)
  wire [7:0] _023_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:432" *)
  wire [15:0] _024_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:428" *)
  wire [7:0] _025_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:432" *)
  wire [15:0] _026_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:428" *)
  wire [7:0] _027_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)
  wire _028_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)
  wire _029_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)
  wire _030_;
  (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)
  wire _031_;
  (* src = "yosys_conv_8_32.v:5" *)
  input clk;
  (* init = 2'h0 *)
  (* src = "yosys_conv_8_32.v:11" *)
  reg [1:0] contador = 2'h0;
  (* src = "yosys_conv_8_32.v:7" *)
  input [7:0] data_in;
  (* src = "yosys_conv_8_32.v:8" *)
  output [31:0] data_out;
  reg [31:0] data_out;
  (* src = "yosys_conv_8_32.v:6" *)
  input valid_0;
  (* src = "yosys_conv_8_32.v:9" *)
  output valid_out;
  reg valid_out;
  assign _004_ = _008_ | _016_;
  assign _008_ = _021_ | _020_;
  assign _007_ = _008_ | _019_;
  assign _009_ = _021_ | _019_;
  assign _005_ = _009_ | _016_;
  assign _010_ = _020_ | _019_;
  assign _006_ = _010_ | _016_;
  assign _013_ = _003_[0] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15" *)  _012_[1];
  assign _014_ = contador[0] |(* src = "yosys_conv_8_32.v:18|conv_8_32.v:15" *)  _012_[1];
  assign _015_ = _003_[0] |(* src = "yosys_conv_8_32.v:17|conv_8_32.v:15" *)  contador[1];
  assign _027_[3] = _026_[3] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[11];
  assign _027_[7] = _026_[7] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[15];
  assign _027_[6] = _026_[6] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[14];
  assign _027_[5] = _026_[5] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[13];
  assign _027_[4] = _026_[4] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[12];
  assign _027_[2] = _026_[2] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[10];
  assign _027_[1] = _026_[1] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[9];
  assign _027_[0] = _026_[0] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _026_[8];
  assign _031_ = _007_ |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)  _016_;
  assign _018_[3] = _017_[3] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[11];
  assign _018_[7] = _017_[7] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[15];
  assign _018_[6] = _017_[6] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[14];
  assign _018_[5] = _017_[5] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[13];
  assign _018_[4] = _017_[4] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[12];
  assign _018_[2] = _017_[2] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[10];
  assign _018_[1] = _017_[1] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[9];
  assign _018_[0] = _017_[0] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _017_[8];
  assign _028_ = _019_ |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)  _004_;
  assign _023_[3] = _022_[3] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[11];
  assign _023_[7] = _022_[7] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[15];
  assign _023_[6] = _022_[6] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[14];
  assign _023_[5] = _022_[5] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[13];
  assign _023_[4] = _022_[4] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[12];
  assign _023_[2] = _022_[2] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[10];
  assign _023_[1] = _022_[1] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[9];
  assign _023_[0] = _022_[0] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _022_[8];
  assign _029_ = _005_ |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)  _020_;
  assign _025_[3] = _024_[3] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[11];
  assign _025_[7] = _024_[7] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[15];
  assign _025_[6] = _024_[6] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[14];
  assign _025_[5] = _024_[5] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[13];
  assign _025_[4] = _024_[4] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[12];
  assign _025_[2] = _024_[2] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[10];
  assign _025_[1] = _024_[1] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[9];
  assign _025_[0] = _024_[0] |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:441" *)  _024_[8];
  assign _030_ = _006_ |(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *)  _021_;
  assign _011_ = contador[0] |(* src = "yosys_conv_8_32.v:16|conv_8_32.v:15" *)  contador[1];
  assign _019_ = ~(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15" *) _013_;
  assign _020_ = ~(* src = "yosys_conv_8_32.v:18|conv_8_32.v:15" *) _014_;
  assign _021_ = ~(* src = "yosys_conv_8_32.v:17|conv_8_32.v:15" *) _015_;
  assign _016_ = ~(* src = "yosys_conv_8_32.v:16|conv_8_32.v:15" *) _011_;
  assign _000_[0] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _003_[0] : 1'h0;
  assign _000_[1] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _003_[1] : 1'h0;
  assign _001_[0] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[0] : data_out[0];
  assign _001_[1] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[1] : data_out[1];
  assign _001_[2] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[2] : data_out[2];
  assign _001_[3] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[3] : data_out[3];
  assign _001_[4] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[4] : data_out[4];
  assign _001_[5] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[5] : data_out[5];
  assign _001_[6] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[6] : data_out[6];
  assign _001_[7] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[7] : data_out[7];
  assign _001_[8] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[8] : data_out[8];
  assign _001_[9] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[9] : data_out[9];
  assign _001_[10] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[10] : data_out[10];
  assign _001_[11] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[11] : data_out[11];
  assign _001_[12] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[12] : data_out[12];
  assign _001_[13] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[13] : data_out[13];
  assign _001_[14] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[14] : data_out[14];
  assign _001_[15] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[15] : data_out[15];
  assign _001_[16] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[16] : data_out[16];
  assign _001_[17] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[17] : data_out[17];
  assign _001_[18] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[18] : data_out[18];
  assign _001_[19] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[19] : data_out[19];
  assign _001_[20] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[20] : data_out[20];
  assign _001_[21] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[21] : data_out[21];
  assign _001_[22] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[22] : data_out[22];
  assign _001_[23] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[23] : data_out[23];
  assign _001_[24] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[24] : data_out[24];
  assign _001_[25] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[25] : data_out[25];
  assign _001_[26] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[26] : data_out[26];
  assign _001_[27] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[27] : data_out[27];
  assign _001_[28] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[28] : data_out[28];
  assign _001_[29] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[29] : data_out[29];
  assign _001_[30] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[30] : data_out[30];
  assign _001_[31] = valid_0 ? (* src = "yosys_conv_8_32.v:14" *) _002_[31] : data_out[31];
  assign _002_[24] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[0] : 1'hx;
  assign _002_[25] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[1] : 1'hx;
  assign _002_[26] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[2] : 1'hx;
  assign _002_[27] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[3] : 1'hx;
  assign _002_[28] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[4] : 1'hx;
  assign _002_[29] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[5] : 1'hx;
  assign _002_[30] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[6] : 1'hx;
  assign _002_[31] = _031_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _027_[7] : 1'hx;
  assign _002_[0] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[0] : 1'hx;
  assign _002_[1] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[1] : 1'hx;
  assign _002_[2] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[2] : 1'hx;
  assign _002_[3] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[3] : 1'hx;
  assign _002_[4] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[4] : 1'hx;
  assign _002_[5] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[5] : 1'hx;
  assign _002_[6] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[6] : 1'hx;
  assign _002_[7] = _028_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _018_[7] : 1'hx;
  assign _002_[8] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[0] : 1'hx;
  assign _002_[9] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[1] : 1'hx;
  assign _002_[10] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[2] : 1'hx;
  assign _002_[11] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[3] : 1'hx;
  assign _002_[12] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[4] : 1'hx;
  assign _002_[13] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[5] : 1'hx;
  assign _002_[14] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[6] : 1'hx;
  assign _002_[15] = _029_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _023_[7] : 1'hx;
  assign _002_[16] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[0] : 1'hx;
  assign _002_[17] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[1] : 1'hx;
  assign _002_[18] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[2] : 1'hx;
  assign _002_[19] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[3] : 1'hx;
  assign _002_[20] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[4] : 1'hx;
  assign _002_[21] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[5] : 1'hx;
  assign _002_[22] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[6] : 1'hx;
  assign _002_[23] = _030_ ? (* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:445" *) _025_[7] : 1'hx;
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      valid_out <= valid_0;
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      contador[0] <= _000_[0];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      contador[1] <= _000_[1];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[0] <= _001_[0];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[1] <= _001_[1];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[2] <= _001_[2];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[3] <= _001_[3];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[4] <= _001_[4];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[5] <= _001_[5];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[6] <= _001_[6];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[7] <= _001_[7];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[8] <= _001_[8];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[9] <= _001_[9];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[10] <= _001_[10];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[11] <= _001_[11];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[12] <= _001_[12];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[13] <= _001_[13];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[14] <= _001_[14];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[15] <= _001_[15];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[16] <= _001_[16];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[17] <= _001_[17];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[18] <= _001_[18];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[19] <= _001_[19];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[20] <= _001_[20];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[21] <= _001_[21];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[22] <= _001_[22];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[23] <= _001_[23];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[24] <= _001_[24];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[25] <= _001_[25];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[26] <= _001_[26];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[27] <= _001_[27];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[28] <= _001_[28];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[29] <= _001_[29];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[30] <= _001_[30];
  (* src = "yosys_conv_8_32.v:13" *)
  always @(posedge clk)
      data_out[31] <= _001_[31];
  assign _012_[1] = contador[1] ^(* src = "yosys_conv_8_32.v:18|conv_8_32.v:15" *)  1'h1;
  assign _026_[8] = data_in[0] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[9] = data_in[1] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[10] = data_in[2] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[11] = data_in[3] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[12] = data_in[4] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[13] = data_in[5] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[14] = data_in[6] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[15] = data_in[7] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _016_;
  assign _026_[0] = data_out[24] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[1] = data_out[25] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[2] = data_out[26] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[3] = data_out[27] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[4] = data_out[28] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[5] = data_out[29] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[6] = data_out[30] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _026_[7] = data_out[31] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _007_;
  assign _017_[8] = data_out[0] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[9] = data_out[1] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[10] = data_out[2] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[11] = data_out[3] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[12] = data_out[4] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[13] = data_out[5] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[14] = data_out[6] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[15] = data_out[7] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _004_;
  assign _017_[0] = data_in[0] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[1] = data_in[1] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[2] = data_in[2] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[3] = data_in[3] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[4] = data_in[4] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[5] = data_in[5] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[6] = data_in[6] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _017_[7] = data_in[7] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _019_;
  assign _022_[8] = data_in[0] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[9] = data_in[1] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[10] = data_in[2] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[11] = data_in[3] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[12] = data_in[4] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[13] = data_in[5] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[14] = data_in[6] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[15] = data_in[7] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _020_;
  assign _022_[0] = data_out[8] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[1] = data_out[9] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[2] = data_out[10] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[3] = data_out[11] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[4] = data_out[12] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[5] = data_out[13] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[6] = data_out[14] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _022_[7] = data_out[15] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _005_;
  assign _024_[8] = data_in[0] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[9] = data_in[1] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[10] = data_in[2] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[11] = data_in[3] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[12] = data_in[4] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[13] = data_in[5] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[14] = data_in[6] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[15] = data_in[7] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _021_;
  assign _024_[0] = data_out[16] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[1] = data_out[17] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[2] = data_out[18] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[3] = data_out[19] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[4] = data_out[20] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[5] = data_out[21] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[6] = data_out[22] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _024_[7] = data_out[23] &(* src = "yosys_conv_8_32.v:19|conv_8_32.v:15|<techmap.v>:434" *)  _006_;
  assign _003_[1] = contador[1] ^(* src = "yosys_conv_8_32.v:22|<techmap.v>:263" *)  contador[0];
  assign _003_[0] = contador[0] ^(* src = "yosys_conv_8_32.v:22|<techmap.v>:262" *)  1'h1;
  assign _003_[31:3] = 29'h00000000;
  assign _012_[0] = _003_[0];
endmodule
