/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "yosys_conv_32_8.v:5" *)
module yosys_conv_32_8(clk, valid_0, data_in, data_out, valid_out);
  (* src = "yosys_conv_32_8.v:13" *)
  wire [1:0] _000_;
  (* src = "yosys_conv_32_8.v:13" *)
  wire [7:0] _001_;
  (* src = "yosys_conv_32_8.v:13" *)
  wire [7:0] _002_;
  (* src = "yosys_conv_32_8.v:22" *)
  (* unused_bits = "2" *)
  wire [31:0] _003_;
  wire [1:0] _004_;
  wire [1:0] _005_;
  wire [1:0] _006_;
  wire [1:0] _007_;
  wire [1:0] _008_;
  wire [1:0] _009_;
  wire [1:0] _010_;
  wire [1:0] _011_;
  wire [1:0] _012_;
  wire _013_;
  wire [1:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:432" *)
  wire [31:0] _019_;
  (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:428" *)
  wire [7:0] _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *)
  wire _024_;
  (* src = "yosys_conv_32_8.v:5" *)
  input clk;
  (* init = 2'h0 *)
  (* src = "yosys_conv_32_8.v:11" *)
  reg [1:0] contador = 2'h0;
  (* src = "yosys_conv_32_8.v:7" *)
  input [31:0] data_in;
  (* src = "yosys_conv_32_8.v:8" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "yosys_conv_32_8.v:6" *)
  input valid_0;
  (* src = "yosys_conv_32_8.v:9" *)
  output valid_out;
  reg valid_out;
  assign _017_ = contador[0] |(* src = "yosys_conv_32_8.v:18|conv_32_8.v:15" *)  _014_[1];
  assign _015_ = _003_[0] |(* src = "yosys_conv_32_8.v:17|conv_32_8.v:15" *)  contador[1];
  assign _004_[0] = _019_[5] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[13];
  assign _004_[1] = _019_[21] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[29];
  assign _020_[5] = _004_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _004_[1];
  assign _005_[0] = _019_[7] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[15];
  assign _005_[1] = _019_[23] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[31];
  assign _020_[7] = _005_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _005_[1];
  assign _006_[0] = _019_[6] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[14];
  assign _006_[1] = _019_[22] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[30];
  assign _020_[6] = _006_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _006_[1];
  assign _007_[0] = _019_[4] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[12];
  assign _007_[1] = _019_[20] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[28];
  assign _020_[4] = _007_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _007_[1];
  assign _008_[0] = _019_[3] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[11];
  assign _008_[1] = _019_[19] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[27];
  assign _020_[3] = _008_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _008_[1];
  assign _009_[0] = _019_[2] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[10];
  assign _009_[1] = _019_[18] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[26];
  assign _020_[2] = _009_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _009_[1];
  assign _010_[0] = _019_[1] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[9];
  assign _010_[1] = _019_[17] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[25];
  assign _020_[1] = _010_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _010_[1];
  assign _011_[0] = _019_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[8];
  assign _011_[1] = _019_[16] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _019_[24];
  assign _020_[0] = _011_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:441" *)  _011_[1];
  assign _012_[0] = _021_ |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *)  _022_;
  assign _012_[1] = _023_ |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *)  _018_;
  assign _024_ = _012_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *)  _012_[1];
  assign _016_ = _003_[0] |(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15" *)  _014_[1];
  assign _013_ = contador[0] |(* src = "yosys_conv_32_8.v:16|conv_32_8.v:15" *)  contador[1];
  assign _022_ = ~(* src = "yosys_conv_32_8.v:18|conv_32_8.v:15" *) _017_;
  assign _023_ = ~(* src = "yosys_conv_32_8.v:17|conv_32_8.v:15" *) _015_;
  assign _018_ = ~(* src = "yosys_conv_32_8.v:16|conv_32_8.v:15" *) _013_;
  assign _021_ = ~(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15" *) _016_;
  assign _000_[0] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _003_[0] : 1'h0;
  assign _000_[1] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _003_[1] : 1'h0;
  assign _001_[0] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[0] : data_out[0];
  assign _001_[1] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[1] : data_out[1];
  assign _001_[2] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[2] : data_out[2];
  assign _001_[3] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[3] : data_out[3];
  assign _001_[4] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[4] : data_out[4];
  assign _001_[5] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[5] : data_out[5];
  assign _001_[6] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[6] : data_out[6];
  assign _001_[7] = valid_0 ? (* src = "yosys_conv_32_8.v:14" *) _002_[7] : data_out[7];
  assign _002_[0] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[0] : 1'hx;
  assign _002_[1] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[1] : 1'hx;
  assign _002_[2] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[2] : 1'hx;
  assign _002_[3] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[3] : 1'hx;
  assign _002_[4] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[4] : 1'hx;
  assign _002_[5] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[5] : 1'hx;
  assign _002_[6] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[6] : 1'hx;
  assign _002_[7] = _024_ ? (* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:445" *) _020_[7] : 1'hx;
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      valid_out <= valid_0;
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      contador[0] <= _000_[0];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      contador[1] <= _000_[1];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[0] <= _001_[0];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[1] <= _001_[1];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[2] <= _001_[2];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[3] <= _001_[3];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[4] <= _001_[4];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[5] <= _001_[5];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[6] <= _001_[6];
  (* src = "yosys_conv_32_8.v:13" *)
  always @(posedge clk)
      data_out[7] <= _001_[7];
  assign _019_[24] = data_in[24] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[25] = data_in[25] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[26] = data_in[26] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[27] = data_in[27] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[28] = data_in[28] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[29] = data_in[29] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[30] = data_in[30] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[31] = data_in[31] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _018_;
  assign _019_[16] = data_in[16] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[17] = data_in[17] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[18] = data_in[18] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[19] = data_in[19] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[20] = data_in[20] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[21] = data_in[21] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[22] = data_in[22] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[23] = data_in[23] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _023_;
  assign _019_[8] = data_in[8] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[9] = data_in[9] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[10] = data_in[10] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[11] = data_in[11] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[12] = data_in[12] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[13] = data_in[13] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[14] = data_in[14] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[15] = data_in[15] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _022_;
  assign _019_[0] = data_in[0] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[1] = data_in[1] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[2] = data_in[2] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[3] = data_in[3] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[4] = data_in[4] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[5] = data_in[5] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[6] = data_in[6] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _019_[7] = data_in[7] &(* src = "yosys_conv_32_8.v:19|conv_32_8.v:15|<techmap.v>:434" *)  _021_;
  assign _003_[1] = contador[1] ^(* src = "yosys_conv_32_8.v:22|<techmap.v>:263" *)  contador[0];
  assign _003_[0] = contador[0] ^(* src = "yosys_conv_32_8.v:22|<techmap.v>:262" *)  1'h1;
  assign _014_[1] = contador[1] ^(* src = "yosys_conv_32_8.v:18|conv_32_8.v:15" *)  1'h1;
  assign _003_[31:3] = 29'h00000000;
  assign _014_[0] = _003_[0];
endmodule
